sudo: required
dist: trusty
language: haxe

env:
  global:
    # deploy_key_decrypt
    - secure: "cWYcbB7z97sW4yZtz9qcYrEhFZktNjQMOraPm7Vy0FsCMqb4r314Fk8rJze+yDbOKGdsIz6VNHE8nlsQN3EgGiVFJnF8xv6GAlfHPuaVomP2vO7W0A+l7xVy2/326MQJP8JoMgdebDi71yxKeEhYA+mVliI9qql9yfD2YOBmilQ="

install_docker: &install_docker
  - sudo apt-get update -qq
  - docker --version
  # https://docs.travis-ci.com/user/docker/#Using-Docker-Compose
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # https://github.com/travis-ci/travis-ci/issues/7008
  - sudo /etc/init.d/mysql stop || true

matrix:
  include:
    # haxe development
    - os: linux
      haxe: development
      env:
        - USE_DOCKER=1
      services: [docker]
      before_install: *install_docker
    # haxe 3.4.4
    - os: linux
      haxe: 3.4.4
      env:
        - USE_DOCKER=1
        - DEPLOY=1
      services: [docker]
      before_install: *install_docker
    # haxe 3.2.1
    - os: linux
      haxe: 3.2.1
      env:
        - USE_DOCKER=1
      services: [docker]
      before_install: *install_docker
    # haxe 3.1.3
    - os: linux
      haxe: 3.1.3
      env:
        - USE_DOCKER=1
      services: [docker]
      before_install: *install_docker
    # Mac
    - os: osx
      haxe: development
    - os: osx
      haxe: 3.4.4
    - os: osx
      haxe: 3.2.1
    - os: osx
      haxe: 3.1.3
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
    fi
  - npm -g install bower
  - haxelib newrepo || mkdir -p .haxelib && haxelib setup .haxelib
  - yes | travis_retry haxelib -notimeout install all
  - yes | travis_retry haxelib -notimeout install tora
  # copy aws.ndll to the right place
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo cp $(haxelib config)/aws-sdk-neko/*/ndll/Mac64/aws.ndll ${NEKOPATH}/aws.ndll;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo cp $(haxelib config)/aws-sdk-neko/*/ndll/Linux64/aws.ndll ${NEKOPATH}/aws.ndll;
    fi;
  - haxelib list
  - haxelib run tora > /dev/null 2>&1 &

script:
  # run our CI script
  - haxe ci.hxml

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: $AWS_REGION
  app: $EB_APP
  env: ${TRAVIS_BRANCH}-lib-haxe-org
  bucket_name: $EB_BUCKET
  zip_file: eb.zip
  on:
    all_branches: true
    condition: $AWS_ACCESS_KEY && $DEPLOY && ($TRAVIS_BRANCH = master || $TRAVIS_BRANCH = development)
