version: "{build}"

services:
  - mysql

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst haxe -y
  - cinst nssm -y
  - cinst curl -y
  - RefreshEnv
  - neko run.n setup haxelib_global
  - haxe libs.hxml
  - haxelib list

build: off

test_script:
  - haxe ci.hxml
